import { SiteData } from './types';

export const initialSiteData: SiteData = {
  brand: {
    name: 'Softvares',
    tagline: 'Web, mobile and AI software development',
    logoType: 'svg-icon',
    logoText: 'Softvares',
    logoImageUrl: '',
    logoCustomSvg: '',
    logoPrimaryColor: '#1b4dff',
  },
  theme: {
    primary: '#1b4dff',
    primaryHover: '#1238d1',
    ink: '#141821',
    inkDark: '#0c1626',
    muted: '#545c6d',
    coral: '#f0492f',
    teal: '#0a9b8b',
    amber: '#f2a900',
    violet: '#7a45e5',
    fontDisplay: "'Bricolage Grotesque', system-ui, sans-serif",
    fontBody: "'Hanken Grotesk', system-ui, -apple-system, sans-serif",
    borderRadius: 8,
  },
  navigation: {
    links: [
      { id: 'services', label: 'Services', href: '#services', hasMegaMenu: 'services' },
      { id: 'industries', label: 'Industries', href: '#industries', hasMegaMenu: 'industries' },
      { id: 'work', label: 'Our work', href: '#work' },
      { id: 'approach', label: 'Approach', href: '#approach' },
      { id: 'insights', label: 'Insights', href: '#insights' },
      { id: 'contact', label: 'Contact', href: '#contact' },
    ],
    portalText: 'Client portal',
    portalHref: '#',
    ctaText: 'Talk to us',
    ctaHref: '#contact',
  },
  hero: {
    autoplay: true,
    autoplayInterval: 8000,
    slides: [
      {
        id: 'slide-1',
        theme: 'cobalt',
        title: 'Software your customers will enjoy using.',
        lead: 'We design and build web and mobile apps that are fast, secure and ready to scale, from the first prototype to millions of users.',
        ctaPrimaryText: 'Start a project',
        ctaPrimaryHref: '#contact',
        ctaSecondaryText: 'See our work',
        ctaSecondaryHref: '#work',
        mockType: 'web-mobile',
        stats: {
          revenue: '$48.2k',
          orders: '1,284',
          conversion: '4.8%',
          balance: '$12,480.50',
        },
      },
      {
        id: 'slide-2',
        theme: 'dark',
        title: 'Put AI to work inside the software you already run.',
        lead: 'Assistants, document processing and forecasting added to your existing workflows, with clear guardrails and results you can measure.',
        ctaPrimaryText: 'Explore AI services',
        ctaPrimaryHref: '#services',
        ctaSecondaryText: 'Book an AI review',
        ctaSecondaryHref: '#contact',
        mockType: 'ai-chat',
        stats: {
          accuracy: '99%',
        },
      },
      {
        id: 'slide-3',
        theme: 'amber',
        title: 'Move to the cloud without pausing your business.',
        lead: 'Modernise legacy systems one service at a time, with zero-downtime releases and infrastructure that costs less to run.',
        ctaPrimaryText: 'Explore cloud services',
        ctaPrimaryHref: '#services',
        ctaSecondaryText: 'Talk to an architect',
        ctaSecondaryHref: '#contact',
        mockType: 'cloud-architecture',
        stats: {
          migrated: '78%',
          costCut: '-32%',
        },
      },
    ],
  },
  techStack: {
    title: 'Built with the tools your teams already trust',
    items: [
      'React',
      'Next.js',
      'Node.js',
      '.NET',
      'Flutter',
      'Swift',
      'Kotlin',
      'Python',
      'PostgreSQL',
      'Azure',
      'AWS',
      'Google Cloud',
      'Kubernetes',
    ],
  },
  services: {
    sectionTitle: 'One team for everything your product needs',
    sectionDesc: 'From the first sketch to the millionth user, choose the capability you need or bring us in end to end.',
    items: [
      {
        id: 'web',
        name: 'Web applications',
        short: 'Portals, SaaS platforms and e-commerce',
        colorKey: 'primary',
        lead: 'Fast, secure and scalable web software that feels as good on a phone as on a desktop. We build customer portals, SaaS platforms, marketplaces and internal tools.',
        points: [
          'Progressive web apps that work offline',
          'Multi-tenant SaaS with billing and roles',
          'E-commerce, catalogues and checkout',
          'Real-time dashboards and reporting',
        ],
        tech: ['React', 'Next.js', 'Node.js', '.NET', 'PostgreSQL'],
        cta: 'Talk about a web project',
      },
      {
        id: 'mobile',
        name: 'Mobile apps',
        short: 'iOS and Android, native or cross-platform',
        colorKey: 'coral',
        lead: 'Native and cross-platform apps that are smooth, secure and approved by the app stores on the first submission. One design language across iPhone, Android and tablet.',
        points: [
          'Swift and Kotlin for maximum performance',
          'Flutter and React Native for one shared codebase',
          'Payments, push notifications and offline mode',
          'Store submission and release management',
        ],
        tech: ['Swift', 'Kotlin', 'Flutter', 'React Native', 'Firebase'],
        cta: 'Talk about a mobile app',
      },
      {
        id: 'ai',
        name: 'AI and automation',
        short: 'Assistants, vision and forecasting',
        colorKey: 'teal',
        lead: 'Practical AI that improves a workflow you already run. We start with one measurable use case, prove the value quickly, and add guardrails before it reaches your customers.',
        points: [
          'Support and internal assistants grounded in your data',
          'Document and invoice processing',
          'Computer vision for quality inspection',
          'Demand and risk forecasting',
        ],
        tech: ['Python', 'LLM APIs', 'PyTorch', 'Vector databases', 'FastAPI'],
        cta: 'Talk about an AI use case',
      },
      {
        id: 'cloud',
        name: 'Cloud and DevOps',
        short: 'Migration, pipelines and monitoring',
        colorKey: 'amber',
        lead: 'Infrastructure that ships every day and stays up. We modernise legacy systems in small, safe steps and give your team the pipelines and monitoring to run them with confidence.',
        points: [
          'Zero-downtime migration from on-premises systems',
          'Automated build, test and release pipelines',
          'Monitoring, alerting and incident playbooks',
          'Cost reviews that lower your monthly bill',
        ],
        tech: ['Azure', 'AWS', 'Google Cloud', 'Kubernetes', 'Terraform'],
        cta: 'Talk to a cloud architect',
      },
      {
        id: 'design',
        name: 'UI and UX design',
        short: 'Research, prototypes and design systems',
        colorKey: 'violet',
        lead: 'Interfaces shaped by research and tested with real people before development starts. Our design systems keep every screen consistent and every release faster.',
        points: [
          'User research and usability testing',
          'Clickable prototypes in days, not weeks',
          'Design systems with reusable components',
          'Accessibility reviews against WCAG 2.2',
        ],
        tech: ['Figma', 'Design tokens', 'Storybook', 'Prototyping', 'Usability testing'],
        cta: 'Talk about a design project',
      },
    ],
  },
  work: {
    sectionTitle: 'Products we have shipped',
    sectionDesc: 'Web and mobile apps used every day by patients, shoppers, drivers, students and finance teams. Select a project to read more.',
    items: [
      {
        id: 'medora',
        name: 'Medora Health',
        industry: 'Healthcare',
        categories: ['mobile', 'web'],
        accentColor: '#0a9b8b',
        mockType: 'phone',
        tagline: 'Telehealth booking and video consults for 300+ clinics.',
        description: 'A patient app and clinic portal that lets people book, pay and join video visits in one flow. Doctors manage schedules, notes and prescriptions from a single web dashboard.',
        techStack: ['Flutter', 'Node.js', 'PostgreSQL', 'WebRTC'],
        results: [
          ['62%', 'faster booking'],
          ['4.8', 'app store rating'],
          ['10 weeks', 'idea to launch'],
        ],
      },
      {
        id: 'kirana',
        name: 'KiranaCart',
        industry: 'Retail',
        categories: ['mobile', 'web'],
        accentColor: '#f0492f',
        mockType: 'phone',
        tagline: 'Neighbourhood grocery ordering with live inventory sync.',
        description: 'Shoppers order from local stores in three taps while shop owners update stock and prices from a simple dashboard. Delivery partners get optimised routes in real time.',
        techStack: ['React Native', 'Next.js', 'Redis', 'Maps API'],
        results: [
          ['2.1x', 'order growth'],
          ['38%', 'lower delivery cost'],
          ['120k', 'monthly users'],
        ],
      },
      {
        id: 'ledger',
        name: 'LedgerLoop',
        industry: 'Finance',
        categories: ['web', 'enterprise'],
        accentColor: '#1b4dff',
        mockType: 'dash',
        tagline: 'Real-time finance dashboard for growing businesses.',
        description: 'A financial operations platform that reconciles bank feeds, automates invoices and forecasts cash flow. Role-based access and full audit trails keep finance teams compliant.',
        techStack: ['React', '.NET', 'Azure', 'SQL Server'],
        results: [
          ['70%', 'less manual work'],
          ['99.99%', 'uptime'],
          ['5 sec', 'report load time'],
        ],
      },
      {
        id: 'fleet',
        name: 'FleetPulse',
        industry: 'Logistics',
        categories: ['enterprise', 'mobile'],
        accentColor: '#f2a900',
        mockType: 'dash',
        tagline: 'Vehicle tracking and dispatch for 8,000 trucks.',
        description: 'Live GPS tracking, driver apps and predictive maintenance alerts in one system. Operations managers see delays before customers do and reroute in a click.',
        techStack: ['React', 'Kotlin', 'Kafka', 'AWS'],
        results: [
          ['18%', 'fuel saved'],
          ['8,000', 'vehicles tracked'],
          ['<2 sec', 'live updates'],
        ],
      },
      {
        id: 'lexa',
        name: 'Lexa Assistant',
        industry: 'Customer support',
        categories: ['ai', 'web'],
        accentColor: '#7a45e5',
        mockType: 'ai',
        tagline: 'An AI agent that resolves support tickets on its own.',
        description: 'A support assistant trained on a company’s own help centre and past tickets. It answers in seconds, hands complex cases to people with full context, and learns from every review.',
        techStack: ['LLM', 'Python', 'Vector DB', 'Next.js'],
        results: [
          ['64%', 'tickets auto-resolved'],
          ['24/7', 'availability'],
          ['3 weeks', 'pilot to production'],
        ],
      },
      {
        id: 'school',
        name: 'SchoolSphere',
        industry: 'Education',
        categories: ['web', 'mobile'],
        accentColor: '#f0492f',
        mockType: 'web',
        tagline: 'A learning platform for 90 schools and 60,000 students.',
        description: 'Live classes, assignments, grading and parent updates in one place. It works on low bandwidth and offline, so lessons continue when the connection does not.',
        techStack: ['Vue', 'Flutter', 'Node.js', 'MongoDB'],
        results: [
          ['60k', 'students'],
          ['91%', 'weekly active use'],
          ['Offline', 'first design'],
        ],
      },
      {
        id: 'stay',
        name: 'StayNest',
        industry: 'Hospitality',
        categories: ['web', 'mobile'],
        accentColor: '#1b4dff',
        mockType: 'web',
        tagline: 'Direct booking and dynamic pricing for boutique hotels.',
        description: 'A direct-booking engine and guest app for independent hotels, with smart pricing, digital check-in and channel manager sync that cuts commission fees.',
        techStack: ['Next.js', 'Swift', 'Stripe', 'GCP'],
        results: [
          ['+31%', 'direct bookings'],
          ['0', 'double bookings'],
          ['9 weeks', 'to launch'],
        ],
      },
      {
        id: 'vision',
        name: 'VisionQC',
        industry: 'Manufacturing',
        categories: ['ai', 'enterprise'],
        accentColor: '#0a9b8b',
        mockType: 'dash',
        tagline: 'Computer vision that inspects products on the factory line.',
        description: 'Cameras and models detect surface defects at line speed and flag them instantly. A web console lets quality teams review, label and retrain the model without engineers.',
        techStack: ['PyTorch', 'FastAPI', 'React', 'Edge devices'],
        results: [
          ['99.2%', 'detection accuracy'],
          ['40 ms', 'per item'],
          ['-55%', 'scrap rate'],
        ],
      },
    ],
  },
  industries: {
    sectionTitle: 'Experience in the industries that run on software',
    sectionDesc: 'We learn your domain first, so the product fits how your people and customers really work.',
    items: [
      {
        id: 'healthcare',
        title: 'Healthcare',
        description: 'Patient apps, telehealth and clinic software that protect privacy and save staff time.',
        iconName: 'heart',
      },
      {
        id: 'finance',
        title: 'Finance',
        description: 'Dashboards, payments and reporting built with the audit trails regulators expect.',
        iconName: 'landmark',
      },
      {
        id: 'retail',
        title: 'Retail and commerce',
        description: 'Storefronts, loyalty and delivery apps that turn browsers into repeat customers.',
        iconName: 'shopping-cart',
      },
      {
        id: 'logistics',
        title: 'Logistics',
        description: 'Tracking, dispatch and driver tools that give operations teams live visibility.',
        iconName: 'truck',
      },
      {
        id: 'education',
        title: 'Education',
        description: 'Learning platforms that work on low bandwidth and keep students, teachers and parents in sync.',
        iconName: 'graduation-cap',
      },
      {
        id: 'manufacturing',
        title: 'Manufacturing',
        description: 'Quality, planning and IoT platforms that connect the factory floor to the business.',
        iconName: 'factory',
      },
    ],
  },
  customerStory: {
    badge: 'Customer story, healthcare',
    quote: 'Patients now book a visit in under a minute, and our releases have been so uneventful we stopped worrying about them.',
    author: 'Anita Rao',
    role: 'Head of Product',
    company: 'Medora Health',
    metrics: [
      ['62%', 'faster booking'],
      ['4.8', 'app store rating'],
      ['10 wks', 'idea to launch'],
    ],
    modalTitle: 'Medora Health Case Study',
    modalDescription: 'Full breakdown of how Softvares engineered an omni-channel telehealth portal and iOS/Android app serving 300+ clinical practices.',
  },
  approach: {
    sectionTitle: 'A clear path from idea to live product',
    sectionDesc: 'Every project follows the same five stages, with a working demo at the end of each two-week sprint so you always see real progress.',
    steps: [
      {
        number: 1,
        title: 'Discover',
        desc: 'A short workshop to agree on goals, users, risks and how success will be measured.',
        duration: '1 to 2 weeks',
      },
      {
        number: 2,
        title: 'Design',
        desc: 'Wireframes and a clickable prototype you can test with real users before code is written.',
        duration: '2 to 3 weeks',
      },
      {
        number: 3,
        title: 'Build',
        desc: 'Two-week sprints with automated tests, peer review and a live demo every cycle.',
        duration: '6 to 16 weeks',
      },
      {
        number: 4,
        title: 'Launch',
        desc: 'Load testing, security review and a monitored release to the web and app stores.',
        duration: '1 to 2 weeks',
      },
      {
        number: 5,
        title: 'Grow',
        desc: 'Analytics, new features and support so the product keeps improving after day one.',
        duration: 'Ongoing',
      },
    ],
    models: [
      {
        id: 'fixed-scope',
        title: 'Fixed-scope project',
        desc: 'For a defined product with clear requirements and a launch date.',
        bestFor: 'MVPs, websites, single apps',
        payment: 'Fixed price, paid by milestone',
        team: 'A squad assembled for your project',
        start: 'Within 2 weeks',
        cta: 'Plan a project',
      },
      {
        id: 'dedicated-team',
        title: 'Dedicated team',
        desc: 'An extension of your own team, working on your roadmap sprint after sprint.',
        bestFor: 'Growing products with a steady backlog',
        payment: 'Monthly, per team member',
        team: 'Engineers, designers and QA',
        start: 'Within 1 week',
        cta: 'Build a team',
      },
      {
        id: 'product-partnership',
        title: 'Product partnership',
        desc: 'A long-term partner from first idea through launch, growth and scale.',
        bestFor: 'Startups and new business lines',
        payment: 'Monthly retainer plus milestones',
        team: 'Product lead and full squad',
        start: 'Within 2 weeks',
        cta: 'Start a partnership',
      },
    ],
  },
  engineering: {
    sectionTitle: 'Engineering standards we never skip',
    sectionDesc: 'Quality and security are part of every sprint, not a step added at the end.',
    pillars: [
      {
        id: 'secure',
        title: 'Secure by design',
        desc: 'Threat modelling, encrypted data and dependency scanning from the first commit.',
        icon: 'shield-check',
      },
      {
        id: 'tested',
        title: 'Tested continuously',
        desc: 'Unit, integration and end-to-end tests run on every change before it can ship.',
        icon: 'flask-conical',
      },
      {
        id: 'accessible',
        title: 'Accessible to everyone',
        desc: 'We design and test against WCAG 2.2 AA so every customer can use what we build.',
        icon: 'accessibility',
      },
      {
        id: 'ownership',
        title: 'You own everything',
        desc: 'Source code, documentation and cloud accounts stay in your name from day one.',
        icon: 'key-round',
      },
    ],
    pipelineReleaseName: 'main / release-2026.09',
    pipelineStatus: 'Released in 3 min 12 s, zero downtime',
    pipelineItems: [
      { id: 'commit', name: 'Commit', desc: 'signed and reviewed', status: 'done' },
      { id: 'build', name: 'Build', desc: '42 s', status: 'done' },
      { id: 'test', name: 'Test', desc: '1,284 passed', status: 'done' },
      { id: 'scan', name: 'Scan', desc: '0 vulnerabilities', status: 'done' },
      { id: 'deploy', name: 'Deploy', desc: 'zero downtime', status: 'done' },
    ],
  },
  insights: {
    sectionTitle: 'Insights from our engineers',
    sectionDesc: 'Practical guidance on building and running modern software.',
    items: [
      {
        id: 'native-vs-cross',
        category: 'Mobile, 8 min read',
        readTime: '8 min read',
        title: 'Native or cross-platform: how to choose the right approach for your mobile app',
        colorKey: 'coral',
        link: '#',
      },
      {
        id: 'ai-checklist',
        category: 'AI, 6 min read',
        readTime: '6 min read',
        title: 'A practical checklist for adding AI to an existing product',
        colorKey: 'teal',
        link: '#',
      },
      {
        id: 'cloud-costs',
        category: 'Cloud, 7 min read',
        readTime: '7 min read',
        title: 'Cutting cloud costs without slowing down releases',
        colorKey: 'amber',
        link: '#',
      },
    ],
  },
  planner: {
    sectionTitle: 'Plan your budget in a minute',
    sectionDesc: 'Choose what you want to build to see a realistic range for cost and time. We confirm exact figures after a short discovery call.',
    types: [
      { key: 'website', label: 'Marketing website', base: 3000, weeks: 3, team: '3 people', includes: 'Design, build, CMS' },
      { key: 'webapp', label: 'Web application', base: 12000, weeks: 8, team: '4 people', includes: 'Design, build, cloud' },
      { key: 'mobile', label: 'Mobile app', base: 15000, weeks: 10, team: '5 people', includes: 'iOS, Android, API' },
      { key: 'both', label: 'Web and mobile', base: 24000, weeks: 14, team: '6 people', includes: 'Web, iOS, Android, API' },
      { key: 'ai', label: 'AI-powered product', base: 18000, weeks: 10, team: '5 people', includes: 'Model, app, evaluation' },
    ],
    scales: [
      { key: 'starter', label: 'Starter (MVP)', costMultiplier: 1.0, weekMultiplier: 1.0 },
      { key: 'growth', label: 'Growth', costMultiplier: 1.6, weekMultiplier: 1.4 },
      { key: 'enterprise', label: 'Enterprise', costMultiplier: 2.6, weekMultiplier: 2.0 },
    ],
    addOns: [
      { key: 'admin', label: 'Admin dashboard', cost: 3000, weeks: 1 },
      { key: 'pay', label: 'Online payments', cost: 2500, weeks: 1 },
      { key: 'ai', label: 'AI assistant', cost: 6000, weeks: 2 },
      { key: 'ana', label: 'Analytics and reports', cost: 2000, weeks: 1 },
      { key: 'cloud', label: 'Cloud and CI/CD', cost: 3000, weeks: 1 },
    ],
    finePrint: 'This is a planning range, not a quote. Final pricing depends on scope, integrations and design depth.',
  },
  contact: {
    title: 'Talk to our team',
    lead: 'Tell us what you want to build. A senior member of our team will reply within one working day.',
    steps: [
      ['We read your brief', 'An engineer and a designer review it together.'],
      ['We book a free 30 minute call', 'To ask questions and share early ideas.'],
      ['You receive a plan', 'Scope, timeline and budget range within 2 working days.'],
    ],
    email: 'softvares.official@gmail.com',
    workingHours: 'Monday to Friday, 9:00 to 18:00 IST',
    whatsappNumber: '+919100850500',
    whatsappDisplayNumber: '+91 9100850500',
    whatsappWelcomeMessage: 'Hi Softvares team, I would like to discuss an engineering project with you.',
    budgetOptions: [
      'Not sure yet',
      'Under $10,000',
      '$10,000 to $30,000',
      '$30,000 to $75,000',
      'Above $75,000',
    ],
  },
  footer: {
    tagline: 'Web, mobile and AI software, designed and engineered for what comes next.',
    location: 'English (India)',
    copyrightYear: 2026,
    servicesTitle: 'Services',
    industriesTitle: 'Industries',
    companyTitle: 'Company',
    supportTitle: 'Support',
    companyLinks: [
      { label: 'Our work', href: '#work' },
      { label: 'Approach', href: '#approach' },
      { label: 'Engineering', href: '#engineering' },
      { label: 'Insights', href: '#insights' },
      { label: 'Careers', href: '#contact' },
    ],
    supportLinks: [
      { label: 'Contact us', href: '#contact' },
      { label: 'Project planner', href: '#estimate' },
      { label: 'Client portal', href: '#' },
      { label: 'Email support', href: 'mailto:softvares.official@gmail.com' },
    ],
    legalLinks: [
      { label: 'Sitemap', href: '#' },
      { label: 'Privacy', href: '#' },
      { label: 'Terms of use', href: '#' },
      { label: 'Accessibility', href: '#' },
    ],
  },
};
